use cross_compile::glsl::GlslCrossCompiler;
use cross_compile::spirv::SpirvShaderCrossCompiler;
use cross_compile::ShaderCrossCompiler;
use itertools::Itertools;
use naga::valid::{Capabilities, ValidationFlags, Validator};
use quote::quote;
use std::collections::HashMap;
use std::path::Path;
use strum::Display;
use type_translator::TypeTranslator;
use versions::SemVer;

mod cross_compile;
mod type_translator;

#[derive(Debug, Ord, PartialOrd, Eq, PartialEq, Hash, Display)]
pub enum ShaderOutputType {
    Glsl,
    Spirv,
}

#[derive(Debug)]
pub struct Builder {
    shader: String,
    enabled_shader_outputs: HashMap<ShaderOutputType, SemVer>,
}

impl Builder {
    pub fn new(path: impl AsRef<Path>) -> Self {
        Self {
            shader: std::fs::read_to_string(path).unwrap(),
            enabled_shader_outputs: HashMap::new(),
        }
    }

    pub fn enable_shader_output(
        mut self,
        kind: ShaderOutputType,
        version: impl TryInto<versions::SemVer>,
    ) -> Self {
        let Ok(version) = version.try_into() else {
            panic!("Invalid version");
        };

        self.enabled_shader_outputs.entry(kind).or_insert(version);

        self
    }

    pub fn generate(self, output_file: impl AsRef<Path>) -> Result<(), Box<dyn std::error::Error>> {
        let output_file = output_file.as_ref();

        let module = naga::front::wgsl::parse_str(&self.shader)?;
        let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
        let module_info = validator.validate(&module)?;

        let shaders: Vec<_> = self
            .enabled_shader_outputs
            .iter()
            .map(|(output_type, version)| {
                match output_type {
                    ShaderOutputType::Glsl => {
                        GlslCrossCompiler::compile(&module, &module_info, version.clone())
                    }
                    ShaderOutputType::Spirv => {
                        SpirvShaderCrossCompiler::compile(&module, &module_info, version.clone())
                    }
                }
                .map(|shaders| (output_type, shaders))
            })
            .try_collect()?;

        let type_translator = TypeTranslator::new(&module);

        let mut output = quote! {
            // This file was generated by wgsl-bindgen
            // Do not edit manually
        };

        for (output_type, (vertex, fragment)) in shaders {
            let output_type = output_type.to_string().to_lowercase();

            output.extend(quote! {
                mod #output_type {
                    #vertex
                    #fragment
                }
            });
        }

        std::fs::write(output_file, output.to_string())?;

        Ok(())
    }
}
