use cross_compile::ShaderCrossCompiler;
use cross_compile::glsl::GlslCrossCompiler;
use cross_compile::spirv::SpirvShaderCrossCompiler;
use naga::ShaderStage;
use naga::valid::{Capabilities, ValidationFlags, Validator};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::HashMap;
use std::path::Path;
use strum::Display;
use syn::parse2;
use type_translator::TypeTranslator;
use versions::SemVer;

mod cross_compile;
mod type_translator;

#[derive(Debug, Ord, PartialOrd, Eq, PartialEq, Hash, Display)]
pub enum ShaderOutputType {
    Glsl,
    Spirv,
}

#[derive(Debug)]
pub struct Builder {
    shader: String,
    shader_output: HashMap<ShaderOutputType, SemVer>,
}

impl Builder {
    pub fn new(path: impl AsRef<Path>) -> Self {
        Self {
            shader: std::fs::read_to_string(path).unwrap(),
            shader_output: HashMap::new(),
        }
    }

    pub fn enable_shader_output(
        mut self,
        kind: ShaderOutputType,
        version: impl TryInto<versions::SemVer>,
    ) -> Self {
        let Ok(version) = version.try_into() else {
            panic!("Invalid version");
        };

        self.shader_output.entry(kind).or_insert(version);

        self
    }

    pub fn generate(self, output_file: impl AsRef<Path>) -> Result<(), Box<dyn std::error::Error>> {
        let output_file = output_file.as_ref();

        let module = naga::front::wgsl::parse_str(&self.shader)?;
        let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
        let module_info = validator.validate(&module)?;

        let vertex_entry = module
            .entry_points
            .iter()
            .find(|e| e.stage == ShaderStage::Vertex)
            .unwrap()
            .name
            .clone();

        let fragment_entry = module
            .entry_points
            .iter()
            .find(|e| e.stage == ShaderStage::Fragment)
            .unwrap()
            .name
            .clone();

        let mut output = TokenStream::default();

        for (output_type, (vertex, fragment)) in
            self.shader_output.iter().map(|(output_type, version)| {
                match output_type {
                    ShaderOutputType::Glsl => GlslCrossCompiler::compile(
                        &module,
                        &module_info,
                        version.clone(),
                        &vertex_entry,
                        &fragment_entry,
                    ),
                    ShaderOutputType::Spirv => SpirvShaderCrossCompiler::compile(
                        &module,
                        &module_info,
                        version.clone(),
                        &vertex_entry,
                        &fragment_entry,
                    ),
                }
                .map(|shaders| (output_type, shaders))
                .expect("Could not cross compile shader")
            })
        {
            let output_type_ident = format_ident!("{}", output_type.to_string().to_lowercase());

            output.extend(quote! {
                pub mod #output_type_ident {
                    pub const VERTEX_SHADER_ENTRY: &str = #vertex_entry;

                    #vertex

                    pub const FRAGMENT_SHADER_ENTRY: &str = #fragment_entry;

                    #fragment
                }
            });
        }

        let type_translator = TypeTranslator::new(&module);
        let structs = type_translator.structs.iter().fold(
            TokenStream::default(),
            |mut structs, struct_def| {
                structs.extend(quote! {
                    #struct_def
                });
                structs
            },
        );

        let output = quote! {
            // This file was generated by wgsl-bindgen
            // Do not edit manually

            #[allow(unused)]
            mod shader {
                #output


                pub mod types {
                    #structs
                }
            }

        };

        let output = parse2(output).unwrap();
        let output_string = prettyplease::unparse(&output);
        std::fs::write(output_file, output_string)?;

        Ok(())
    }
}
