use multiemu_machine::processor::instruction::{InstructionSet, InstructionTextRepresentation};
use std::borrow::Cow;

// https://www.pagetable.com/c64ref/6502/?tab=2


#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum AddressingMode {
    Accumulator,
    Immediate(u8),
    Absolute(u16),
    XIndexedAbsolute(u16),
    YIndexedAbsolute(u16),
    AbsoluteIndirect(u16),
    ZeroPage(u8),
    XIndexedZeroPage(u8),
    YIndexedZeroPage(u8),
    XIndexedZeroPageIndirect(u8),
    ZeroPageIndirectYIndexed(u8),
    Relative(i8),
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum M6502InstructionSetSpecifier {
    Adc,
    Anc,
    And,
    Arr,
    Asl,
    Asr,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dcp,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Isc,
    Jam,
    Jmp,
    Jsr,
    Las,
    Lax,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rla,
    Rol,
    Ror,
    Rra,
    Rti,
    Rts,
    Sax,
    Sbc,
    Sbx,
    Sec,
    Sed,
    Sei,
    Sha,
    Shs,
    Shx,
    Shy,
    Slo,
    Sre,
    Sta,
    Stx,
    Sty,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
    Xaa,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct M6502InstructionSet {
    pub specifier: M6502InstructionSetSpecifier,
    pub addressing_mode: Option<AddressingMode>,
}

impl M6502InstructionSet {
    pub fn is_addressing_mode_valid(&self) -> bool {
        match self.specifier {
            M6502InstructionSetSpecifier::Adc => todo!(),
            M6502InstructionSetSpecifier::Anc => todo!(),
            M6502InstructionSetSpecifier::And => todo!(),
            M6502InstructionSetSpecifier::Arr => todo!(),
            M6502InstructionSetSpecifier::Asl => todo!(),
            M6502InstructionSetSpecifier::Asr => todo!(),
            M6502InstructionSetSpecifier::Bcc => todo!(),
            M6502InstructionSetSpecifier::Bcs => todo!(),
            M6502InstructionSetSpecifier::Beq => todo!(),
            M6502InstructionSetSpecifier::Bit => todo!(),
            M6502InstructionSetSpecifier::Bmi => todo!(),
            M6502InstructionSetSpecifier::Bne => todo!(),
            M6502InstructionSetSpecifier::Bpl => todo!(),
            M6502InstructionSetSpecifier::Brk => todo!(),
            M6502InstructionSetSpecifier::Bvc => todo!(),
            M6502InstructionSetSpecifier::Bvs => todo!(),
            M6502InstructionSetSpecifier::Clc => todo!(),
            M6502InstructionSetSpecifier::Cld => todo!(),
            M6502InstructionSetSpecifier::Cli => todo!(),
            M6502InstructionSetSpecifier::Clv => todo!(),
            M6502InstructionSetSpecifier::Cmp => todo!(),
            M6502InstructionSetSpecifier::Cpx => todo!(),
            M6502InstructionSetSpecifier::Cpy => todo!(),
            M6502InstructionSetSpecifier::Dcp => todo!(),
            M6502InstructionSetSpecifier::Dec => todo!(),
            M6502InstructionSetSpecifier::Dex => todo!(),
            M6502InstructionSetSpecifier::Dey => todo!(),
            M6502InstructionSetSpecifier::Eor => todo!(),
            M6502InstructionSetSpecifier::Inc => todo!(),
            M6502InstructionSetSpecifier::Inx => todo!(),
            M6502InstructionSetSpecifier::Iny => todo!(),
            M6502InstructionSetSpecifier::Isc => todo!(),
            M6502InstructionSetSpecifier::Jam => todo!(),
            M6502InstructionSetSpecifier::Jmp => todo!(),
            M6502InstructionSetSpecifier::Jsr => todo!(),
            M6502InstructionSetSpecifier::Las => todo!(),
            M6502InstructionSetSpecifier::Lax => todo!(),
            M6502InstructionSetSpecifier::Lda => todo!(),
            M6502InstructionSetSpecifier::Ldx => todo!(),
            M6502InstructionSetSpecifier::Ldy => todo!(),
            M6502InstructionSetSpecifier::Lsr => todo!(),
            M6502InstructionSetSpecifier::Nop => todo!(),
            M6502InstructionSetSpecifier::Ora => todo!(),
            M6502InstructionSetSpecifier::Pha => todo!(),
            M6502InstructionSetSpecifier::Php => todo!(),
            M6502InstructionSetSpecifier::Pla => todo!(),
            M6502InstructionSetSpecifier::Plp => todo!(),
            M6502InstructionSetSpecifier::Rla => todo!(),
            M6502InstructionSetSpecifier::Rol => todo!(),
            M6502InstructionSetSpecifier::Ror => todo!(),
            M6502InstructionSetSpecifier::Rra => todo!(),
            M6502InstructionSetSpecifier::Rti => todo!(),
            M6502InstructionSetSpecifier::Rts => todo!(),
            M6502InstructionSetSpecifier::Sax => todo!(),
            M6502InstructionSetSpecifier::Sbc => todo!(),
            M6502InstructionSetSpecifier::Sbx => todo!(),
            M6502InstructionSetSpecifier::Sec => todo!(),
            M6502InstructionSetSpecifier::Sed => todo!(),
            M6502InstructionSetSpecifier::Sei => todo!(),
            M6502InstructionSetSpecifier::Sha => todo!(),
            M6502InstructionSetSpecifier::Shs => todo!(),
            M6502InstructionSetSpecifier::Shx => todo!(),
            M6502InstructionSetSpecifier::Shy => todo!(),
            M6502InstructionSetSpecifier::Slo => todo!(),
            M6502InstructionSetSpecifier::Sre => todo!(),
            M6502InstructionSetSpecifier::Sta => todo!(),
            M6502InstructionSetSpecifier::Stx => todo!(),
            M6502InstructionSetSpecifier::Sty => todo!(),
            M6502InstructionSetSpecifier::Tax => todo!(),
            M6502InstructionSetSpecifier::Tay => todo!(),
            M6502InstructionSetSpecifier::Tsx => todo!(),
            M6502InstructionSetSpecifier::Txa => todo!(),
            M6502InstructionSetSpecifier::Txs => todo!(),
            M6502InstructionSetSpecifier::Tya => todo!(),
            M6502InstructionSetSpecifier::Xaa => todo!(),
        }
    }
}

impl InstructionSet for M6502InstructionSet {
    fn to_text_representation(&self) -> InstructionTextRepresentation {
        InstructionTextRepresentation {
            instruction_mnemonic: Cow::Borrowed(match self.specifier {
                M6502InstructionSetSpecifier::Adc => "ADC",
                M6502InstructionSetSpecifier::Anc => "ANC",
                M6502InstructionSetSpecifier::And => "AND",
                M6502InstructionSetSpecifier::Arr => "ARR",
                M6502InstructionSetSpecifier::Asl => "ASL",
                M6502InstructionSetSpecifier::Asr => "ASR",
                M6502InstructionSetSpecifier::Bcc => "BCC",
                M6502InstructionSetSpecifier::Bcs => "BCS",
                M6502InstructionSetSpecifier::Beq => "BEQ",
                M6502InstructionSetSpecifier::Bit => "BIT",
                M6502InstructionSetSpecifier::Bmi => "BMI",
                M6502InstructionSetSpecifier::Bne => "BNE",
                M6502InstructionSetSpecifier::Bpl => "BPL",
                M6502InstructionSetSpecifier::Brk => "BRK",
                M6502InstructionSetSpecifier::Bvc => "BVC",
                M6502InstructionSetSpecifier::Bvs => "BVS",
                M6502InstructionSetSpecifier::Clc => "CLC",
                M6502InstructionSetSpecifier::Cld => "CLD",
                M6502InstructionSetSpecifier::Cli => "CLI",
                M6502InstructionSetSpecifier::Clv => "CLV",
                M6502InstructionSetSpecifier::Cmp => "CMP",
                M6502InstructionSetSpecifier::Cpx => "CPX",
                M6502InstructionSetSpecifier::Cpy => "CPY",
                M6502InstructionSetSpecifier::Dcp => "DCP",
                M6502InstructionSetSpecifier::Dec => "DEC",
                M6502InstructionSetSpecifier::Dex => "DEX",
                M6502InstructionSetSpecifier::Dey => "DEY",
                M6502InstructionSetSpecifier::Eor => "EOR",
                M6502InstructionSetSpecifier::Inc => "INC",
                M6502InstructionSetSpecifier::Inx => "INX",
                M6502InstructionSetSpecifier::Iny => "INY",
                M6502InstructionSetSpecifier::Isc => "ISC",
                M6502InstructionSetSpecifier::Jam => "JAM",
                M6502InstructionSetSpecifier::Jmp => "JMP",
                M6502InstructionSetSpecifier::Jsr => "JSR",
                M6502InstructionSetSpecifier::Las => "LAS",
                M6502InstructionSetSpecifier::Lax => "LAX",
                M6502InstructionSetSpecifier::Lda => "LDA",
                M6502InstructionSetSpecifier::Ldx => "LDX",
                M6502InstructionSetSpecifier::Ldy => "LDY",
                M6502InstructionSetSpecifier::Lsr => "LSR",
                M6502InstructionSetSpecifier::Nop => "NOP",
                M6502InstructionSetSpecifier::Ora => "ORA",
                M6502InstructionSetSpecifier::Pha => "PHA",
                M6502InstructionSetSpecifier::Php => "PHP",
                M6502InstructionSetSpecifier::Pla => "PLA",
                M6502InstructionSetSpecifier::Plp => "PLP",
                M6502InstructionSetSpecifier::Rla => "RLA",
                M6502InstructionSetSpecifier::Rol => "ROL",
                M6502InstructionSetSpecifier::Ror => "ROR",
                M6502InstructionSetSpecifier::Rra => "RRA",
                M6502InstructionSetSpecifier::Rti => "RTI",
                M6502InstructionSetSpecifier::Rts => "RTS",
                M6502InstructionSetSpecifier::Sax => "SAX",
                M6502InstructionSetSpecifier::Sbc => "SBC",
                M6502InstructionSetSpecifier::Sbx => "SBX",
                M6502InstructionSetSpecifier::Sec => "SEC",
                M6502InstructionSetSpecifier::Sed => "SED",
                M6502InstructionSetSpecifier::Sei => "SEI",
                M6502InstructionSetSpecifier::Sha => "SHA",
                M6502InstructionSetSpecifier::Shs => "SHS",
                M6502InstructionSetSpecifier::Shx => "SHX",
                M6502InstructionSetSpecifier::Shy => "SHY",
                M6502InstructionSetSpecifier::Slo => "SLO",
                M6502InstructionSetSpecifier::Sre => "SRE",
                M6502InstructionSetSpecifier::Sta => "STA",
                M6502InstructionSetSpecifier::Stx => "STX",
                M6502InstructionSetSpecifier::Sty => "STY",
                M6502InstructionSetSpecifier::Tax => "TAX",
                M6502InstructionSetSpecifier::Tay => "TAY",
                M6502InstructionSetSpecifier::Tsx => "TSX",
                M6502InstructionSetSpecifier::Txa => "TXA",
                M6502InstructionSetSpecifier::Txs => "TXS",
                M6502InstructionSetSpecifier::Tya => "TYA",
                M6502InstructionSetSpecifier::Xaa => "XAA",
            }),
        }
    }

    fn cycles_taken(&self) -> u8 {
        match self.specifier {
            M6502InstructionSetSpecifier::Adc
            | M6502InstructionSetSpecifier::And
            | M6502InstructionSetSpecifier::Cmp
            | M6502InstructionSetSpecifier::Lax
            | M6502InstructionSetSpecifier::Lda
            | M6502InstructionSetSpecifier::Ora
            | M6502InstructionSetSpecifier::Sbc
            | M6502InstructionSetSpecifier::Eor
            | M6502InstructionSetSpecifier::Ldx
            | M6502InstructionSetSpecifier::Ldy => match self.addressing_mode {
                Some(AddressingMode::Immediate(..)) => 2,
                Some(AddressingMode::Absolute(..)) => 4,
                Some(AddressingMode::XIndexedAbsolute(..)) => 4,
                Some(AddressingMode::YIndexedAbsolute(..)) => 4,
                Some(AddressingMode::ZeroPage(..)) => 3,
                Some(AddressingMode::XIndexedZeroPage(..)) => 4,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 6,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 5,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Anc => 2,
            M6502InstructionSetSpecifier::Arr => 2,
            M6502InstructionSetSpecifier::Asl
            | M6502InstructionSetSpecifier::Lsr
            | M6502InstructionSetSpecifier::Rol
            | M6502InstructionSetSpecifier::Ror => match self.addressing_mode {
                Some(AddressingMode::Accumulator) => 2,
                Some(AddressingMode::Absolute(..)) => 6,
                Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                Some(AddressingMode::ZeroPage(..)) => 5,
                Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Asr => 2,
            M6502InstructionSetSpecifier::Bcc => 2,
            M6502InstructionSetSpecifier::Bcs => 2,
            M6502InstructionSetSpecifier::Beq => 2,
            M6502InstructionSetSpecifier::Bit => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 4,
                Some(AddressingMode::ZeroPage(..)) => 3,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Bmi => 2,
            M6502InstructionSetSpecifier::Bne => 2,
            M6502InstructionSetSpecifier::Bpl => 2,
            M6502InstructionSetSpecifier::Brk => 7,
            M6502InstructionSetSpecifier::Bvc => 2,
            M6502InstructionSetSpecifier::Bvs => 2,
            M6502InstructionSetSpecifier::Clc => 2,
            M6502InstructionSetSpecifier::Cld => 2,
            M6502InstructionSetSpecifier::Cli => 2,
            M6502InstructionSetSpecifier::Clv => 2,
            M6502InstructionSetSpecifier::Cpx | M6502InstructionSetSpecifier::Cpy => {
                match self.addressing_mode {
                    Some(AddressingMode::Immediate(..)) => 2,
                    Some(AddressingMode::Absolute(..)) => 4,
                    Some(AddressingMode::ZeroPage(..)) => 3,
                    _ => unreachable!(),
                }
            }
            M6502InstructionSetSpecifier::Dcp => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 6,
                Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                Some(AddressingMode::YIndexedAbsolute(..)) => 7,
                Some(AddressingMode::ZeroPage(..)) => 5,
                Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 8,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 6,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Dec | M6502InstructionSetSpecifier::Inc => {
                match self.addressing_mode {
                    Some(AddressingMode::Absolute(..)) => 6,
                    Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                    Some(AddressingMode::ZeroPage(..)) => 5,
                    Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                    _ => unreachable!(),
                }
            }
            M6502InstructionSetSpecifier::Dex | M6502InstructionSetSpecifier::Dey => 2,
            M6502InstructionSetSpecifier::Inx | M6502InstructionSetSpecifier::Iny => 2,
            M6502InstructionSetSpecifier::Isc => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 6,
                Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                Some(AddressingMode::YIndexedAbsolute(..)) => 7,
                Some(AddressingMode::ZeroPage(..)) => 5,
                Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 8,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 8,
                _ => unreachable!(),
            },
            // This is actually infinite
            M6502InstructionSetSpecifier::Jam => 2,
            M6502InstructionSetSpecifier::Jmp => 1,
            M6502InstructionSetSpecifier::Jsr => 6,
            M6502InstructionSetSpecifier::Las => 4,
            M6502InstructionSetSpecifier::Nop => match self.addressing_mode {
                None => 2,
                Some(AddressingMode::Immediate(..)) => 2,
                Some(AddressingMode::Absolute(..)) => 4,
                Some(AddressingMode::XIndexedAbsolute(..)) => 4,
                Some(AddressingMode::ZeroPage(..)) => 3,
                Some(AddressingMode::XIndexedZeroPage(..)) => 4,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Pha => 3,
            M6502InstructionSetSpecifier::Php => 3,
            M6502InstructionSetSpecifier::Pla => 4,
            M6502InstructionSetSpecifier::Plp => 4,
            M6502InstructionSetSpecifier::Rla | M6502InstructionSetSpecifier::Rra => {
                match self.addressing_mode {
                    Some(AddressingMode::Absolute(..)) => 6,
                    Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                    Some(AddressingMode::YIndexedAbsolute(..)) => 7,
                    Some(AddressingMode::ZeroPage(..)) => 5,
                    Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                    Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 8,
                    Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 8,
                    _ => unreachable!(),
                }
            }
            M6502InstructionSetSpecifier::Rti => 6,
            M6502InstructionSetSpecifier::Rts => 6,
            M6502InstructionSetSpecifier::Sax => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 4,
                Some(AddressingMode::ZeroPage(..)) => 3,
                Some(AddressingMode::YIndexedZeroPage(..)) => 4,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 6,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Sbx => 2,
            M6502InstructionSetSpecifier::Sec
            | M6502InstructionSetSpecifier::Sed
            | M6502InstructionSetSpecifier::Sei => 2,
            M6502InstructionSetSpecifier::Sha => match self.addressing_mode {
                Some(AddressingMode::YIndexedAbsolute(..)) => 5,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 6,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Shs => 5,
            M6502InstructionSetSpecifier::Shx => 5,
            M6502InstructionSetSpecifier::Shy => 5,
            M6502InstructionSetSpecifier::Slo => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 6,
                Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                Some(AddressingMode::YIndexedAbsolute(..)) => 7,
                Some(AddressingMode::ZeroPage(..)) => 5,
                Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 8,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 8,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Sre => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 6,
                Some(AddressingMode::XIndexedAbsolute(..)) => 7,
                Some(AddressingMode::YIndexedAbsolute(..)) => 7,
                Some(AddressingMode::ZeroPage(..)) => 5,
                Some(AddressingMode::XIndexedZeroPage(..)) => 6,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 8,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 8,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Sta => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 5,
                Some(AddressingMode::XIndexedAbsolute(..)) => 6,
                Some(AddressingMode::YIndexedAbsolute(..)) => 6,
                Some(AddressingMode::ZeroPage(..)) => 3,
                Some(AddressingMode::XIndexedZeroPage(..)) => 4,
                Some(AddressingMode::XIndexedZeroPageIndirect(..)) => 6,
                Some(AddressingMode::ZeroPageIndirectYIndexed(..)) => 6,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Stx => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 4,
                Some(AddressingMode::ZeroPage(..)) => 3,
                Some(AddressingMode::YIndexedZeroPage(..)) => 4,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Sty => match self.addressing_mode {
                Some(AddressingMode::Absolute(..)) => 4,
                Some(AddressingMode::ZeroPage(..)) => 3,
                Some(AddressingMode::XIndexedZeroPage(..)) => 4,
                _ => unreachable!(),
            },
            M6502InstructionSetSpecifier::Tax => 2,
            M6502InstructionSetSpecifier::Tay => 2,
            M6502InstructionSetSpecifier::Tsx => 2,
            M6502InstructionSetSpecifier::Txa => 2,
            M6502InstructionSetSpecifier::Txs => 2,
            M6502InstructionSetSpecifier::Tya => 2,
            M6502InstructionSetSpecifier::Xaa => 2,
        }
    }
}
