use multiemu_machine::processor::instruction::InstructionSet;
use serde::{Deserialize, Serialize};
use std::fmt::Display;

// https://www.pagetable.com/c64ref/6502/?tab=2

#[derive(Debug, Copy, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AddressingMode {
    Immediate,
    Absolute,
    XIndexedAbsolute,
    YIndexedAbsolute,
    AbsoluteIndirect,
    ZeroPage,
    XIndexedZeroPage,
    YIndexedZeroPage,
    XIndexedZeroPageIndirect,
    ZeroPageIndirectYIndexed,
    Relative,
    Accumulator,
}

impl AddressingMode {
    pub fn added_instruction_length(&self) -> u16 {
        match self {
            AddressingMode::Immediate => 1,
            AddressingMode::Absolute => 2,
            AddressingMode::XIndexedAbsolute => 2,
            AddressingMode::YIndexedAbsolute => 2,
            AddressingMode::AbsoluteIndirect => 2,
            AddressingMode::ZeroPage => 1,
            AddressingMode::XIndexedZeroPage => 1,
            AddressingMode::YIndexedZeroPage => 1,
            AddressingMode::XIndexedZeroPageIndirect => 1,
            AddressingMode::ZeroPageIndirectYIndexed => 1,
            AddressingMode::Relative => 1,
            AddressingMode::Accumulator => 0,
        }
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Opcode {
    Adc,
    Anc,
    And,
    Arr,
    Asl,
    Asr,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Brk,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Dcp,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Isc,
    Jam,
    Jmp,
    Jsr,
    Las,
    Lax,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Nop,
    Ora,
    Pha,
    Php,
    Pla,
    Plp,
    Rla,
    Rol,
    Ror,
    Rra,
    Rti,
    Rts,
    Sax,
    Sbc,
    Sbx,
    Sec,
    Sed,
    Sei,
    Sha,
    Shs,
    Shx,
    Shy,
    Slo,
    Sre,
    Sta,
    Stx,
    Sty,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
    Xaa,
}

impl Display for Opcode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let string = match self {
            Opcode::Adc => "ADC",
            Opcode::Anc => "ANC",
            Opcode::And => "AND",
            Opcode::Arr => "ARR",
            Opcode::Asl => "ASL",
            Opcode::Asr => "ASR",
            Opcode::Bcc => "BCC",
            Opcode::Bcs => "BCS",
            Opcode::Beq => "BEQ",
            Opcode::Bit => "BIT",
            Opcode::Bmi => "BMI",
            Opcode::Bne => "BNE",
            Opcode::Bpl => "BPL",
            Opcode::Brk => "BRK",
            Opcode::Bvc => "BVC",
            Opcode::Bvs => "BVS",
            Opcode::Clc => "CLC",
            Opcode::Cld => "CLD",
            Opcode::Cli => "CLI",
            Opcode::Clv => "CLV",
            Opcode::Cmp => "CMP",
            Opcode::Cpx => "CPX",
            Opcode::Cpy => "CPY",
            Opcode::Dcp => "DCP",
            Opcode::Dec => "DEC",
            Opcode::Dex => "DEX",
            Opcode::Dey => "DEY",
            Opcode::Eor => "EOR",
            Opcode::Inc => "INC",
            Opcode::Inx => "INX",
            Opcode::Iny => "INY",
            Opcode::Isc => "ISC",
            Opcode::Jam => "JAM",
            Opcode::Jmp => "JMP",
            Opcode::Jsr => "JSR",
            Opcode::Las => "LAS",
            Opcode::Lax => "LAX",
            Opcode::Lda => "LDA",
            Opcode::Ldx => "LDX",
            Opcode::Ldy => "LDY",
            Opcode::Lsr => "LSR",
            Opcode::Nop => "NOP",
            Opcode::Ora => "ORA",
            Opcode::Pha => "PHA",
            Opcode::Php => "PHP",
            Opcode::Pla => "PLA",
            Opcode::Plp => "PLP",
            Opcode::Rla => "RLA",
            Opcode::Rol => "ROL",
            Opcode::Ror => "ROR",
            Opcode::Rra => "RRA",
            Opcode::Rti => "RTI",
            Opcode::Rts => "RTS",
            Opcode::Sax => "SAX",
            Opcode::Sbc => "SBC",
            Opcode::Sbx => "SBX",
            Opcode::Sec => "SEC",
            Opcode::Sed => "SED",
            Opcode::Sei => "SEI",
            Opcode::Sha => "SHA",
            Opcode::Shs => "SHS",
            Opcode::Shx => "SHX",
            Opcode::Shy => "SHY",
            Opcode::Slo => "SLO",
            Opcode::Sre => "SRE",
            Opcode::Sta => "STA",
            Opcode::Stx => "STX",
            Opcode::Sty => "STY",
            Opcode::Tax => "TAX",
            Opcode::Tay => "TAY",
            Opcode::Tsx => "TSX",
            Opcode::Txa => "TXA",
            Opcode::Txs => "TXS",
            Opcode::Tya => "TYA",
            Opcode::Xaa => "XAA",
        };

        f.write_str(string)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct M6502InstructionSet {
    pub opcode: Opcode,
    pub addressing_mode: Option<AddressingMode>,
}

impl M6502InstructionSet {
    pub fn is_addressing_mode_valid(&self) -> bool {
        match self.opcode {
            Opcode::Adc => todo!(),
            Opcode::Anc => todo!(),
            Opcode::And => todo!(),
            Opcode::Arr => todo!(),
            Opcode::Asl => todo!(),
            Opcode::Asr => todo!(),
            Opcode::Bcc => todo!(),
            Opcode::Bcs => todo!(),
            Opcode::Beq => todo!(),
            Opcode::Bit => todo!(),
            Opcode::Bmi => todo!(),
            Opcode::Bne => todo!(),
            Opcode::Bpl => todo!(),
            Opcode::Brk => todo!(),
            Opcode::Bvc => todo!(),
            Opcode::Bvs => todo!(),
            Opcode::Clc => todo!(),
            Opcode::Cld => todo!(),
            Opcode::Cli => todo!(),
            Opcode::Clv => todo!(),
            Opcode::Cmp => todo!(),
            Opcode::Cpx => todo!(),
            Opcode::Cpy => todo!(),
            Opcode::Dcp => todo!(),
            Opcode::Dec => todo!(),
            Opcode::Dex => todo!(),
            Opcode::Dey => todo!(),
            Opcode::Eor => todo!(),
            Opcode::Inc => todo!(),
            Opcode::Inx => todo!(),
            Opcode::Iny => todo!(),
            Opcode::Isc => todo!(),
            Opcode::Jam => todo!(),
            Opcode::Jmp => todo!(),
            Opcode::Jsr => todo!(),
            Opcode::Las => todo!(),
            Opcode::Lax => todo!(),
            Opcode::Lda => todo!(),
            Opcode::Ldx => todo!(),
            Opcode::Ldy => todo!(),
            Opcode::Lsr => todo!(),
            Opcode::Nop => todo!(),
            Opcode::Ora => todo!(),
            Opcode::Pha => todo!(),
            Opcode::Php => todo!(),
            Opcode::Pla => todo!(),
            Opcode::Plp => todo!(),
            Opcode::Rla => todo!(),
            Opcode::Rol => todo!(),
            Opcode::Ror => todo!(),
            Opcode::Rra => todo!(),
            Opcode::Rti => todo!(),
            Opcode::Rts => todo!(),
            Opcode::Sax => todo!(),
            Opcode::Sbc => todo!(),
            Opcode::Sbx => todo!(),
            Opcode::Sec => todo!(),
            Opcode::Sed => todo!(),
            Opcode::Sei => todo!(),
            Opcode::Sha => todo!(),
            Opcode::Shs => todo!(),
            Opcode::Shx => todo!(),
            Opcode::Shy => todo!(),
            Opcode::Slo => todo!(),
            Opcode::Sre => todo!(),
            Opcode::Sta => todo!(),
            Opcode::Stx => todo!(),
            Opcode::Sty => todo!(),
            Opcode::Tax => todo!(),
            Opcode::Tay => todo!(),
            Opcode::Tsx => todo!(),
            Opcode::Txa => todo!(),
            Opcode::Txs => todo!(),
            Opcode::Tya => todo!(),
            Opcode::Xaa => todo!(),
        }
    }
}

impl InstructionSet for M6502InstructionSet {
    type Opcode = Opcode;
    type AddressingMode = AddressingMode;
}
